// ClaudeTranslator: translates a batch of lines using the Anthropic API.
// Expects `log` to be available on the global scope (shared/log.js).
// Returns Map[linenumber] = translation
// Generated by Claude.
const ClaudeTranslator = {
  async translate(lines, language, apiKey) {
    const nonEmpty = lines.filter((l) => l.trim());
    if (!nonEmpty.length) return new Map(lines.map((l) => [l, l]));

    const numbered = nonEmpty.map((l, i) => `${i + 1}. ${l}`).join("\n");

    const model = "claude-haiku-4-5";
    log("Claude API request", { model, language, lines: nonEmpty.length });

    const t0 = Date.now();
    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model,
        max_tokens: 2048,
        messages: [
          {
            role: "user",
            content: `Translate the following song lyrics to ${language}. Return ONLY the translations, one per line, numbered the same way. Do not add any explanation or commentary.\n\n${numbered}`,
          },
        ],
      }),
    });

    log("Claude API response", {
      status: response.status,
      ok: response.ok,
      ms: Date.now() - t0,
    });

    if (!response.ok) {
      const err = await response.text();
      log("Claude API error body", { err });
      return new Map(lines.map((l) => [l, l]));
    }

    const data = await response.json();
    const text = data.content?.[0]?.text ?? "";

    const input_tokens = data.usage?.input_tokens ?? 0;
    const output_tokens = data.usage?.output_tokens ?? 0;
    log("Claude API usage", {
      input_tokens,
      output_tokens,
      stop_reason: data.stop_reason,
    });

    browser.storage.local
      .get({ tokenUsage: { input_tokens: 0, output_tokens: 0 } })
      .then(({ tokenUsage }) => {
        browser.storage.local.set({
          tokenUsage: {
            input_tokens: tokenUsage.input_tokens + input_tokens,
            output_tokens: tokenUsage.output_tokens + output_tokens,
          },
        });
      });

    // Parse numbered response back into a Map keyed by original line
    const translationMap = new Map(lines.map((l) => [l, l]));
    const resultLines = text.split(/\r\n|\r|\n/);
    for (const resultLine of resultLines) {
      const match = resultLine.match(/^(\d+)\.\s*(.*)/);
      if (match) {
        const idx = parseInt(match[1], 10) - 1;
        if (idx >= 0 && idx < nonEmpty.length) {
          translationMap.set(nonEmpty[idx], match[2].trim());
        }
      }
    }

    return translationMap;
  },
};
